import { StyleSheet } from 'react-native';

export const modalStyles = StyleSheet.create({
  mask: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1000,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modal: {
    position: 'relative',
    width: 420,
    maxWidth: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    boxShadow: '0 9px 28px rgba(0, 0, 0, 0.12)',
    overflow: 'hidden',
  },
  close: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: 'transparent',
  },
  header: {
    paddingVertical: 16,
    paddingHorizontal: 24,
    paddingRight: 48,
    fontSize: 16,
    fontWeight: '600',
    color: 'rgba(0, 0, 0, 0.88)',
  },
  body: {
    paddingVertical: 20,
    paddingHorizontal: 24,
    gap: 10,
  },
  footer: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(5, 5, 5, 0.06)',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  button: {
    minWidth: 72,
    height: 32,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    backgroundColor: '#ffffff',
  },
  primaryButton: {
    backgroundColor: '#1677ff',
    borderColor: '#1677ff',
  },
  buttonText: {
    color: 'rgba(0, 0, 0, 0.88)',
    fontSize: 14,
  },
  primaryButtonText: {
    color: '#ffffff',
  },
  input: {
    width: '100%',
    height: 36,
    paddingHorizontal: 11,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    fontSize: 14,
  },
});
